server:
  port: 8090
  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb2
    username: root
    password: GOMATHIc@06
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
  application:
    name: BOOKING-SERVICE